In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import seaborn as sns
import re
import statsmodels.stats.api as sms

In [2]:
from scipy.stats import chi2_contingency

# Создание датафрейма
df = pd.DataFrame({
    '': ['Увеличивается сумма покупки', 'Не меняется сумма покупки', 'Уменьшается сумма покупки'],
    'men': [21, 75, 5],
    'women': [16, 60, 10]
})

# Создание таблицы сопряженности
cross_table = pd.crosstab(df[''], [df['men'], df['women']])

# Применение хи-квадрат теста
chi2, p_value, dof, expected = chi2_contingency(cross_table)

# Вывод значения
print("Chi-square statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:", expected)


Chi-square statistic: 6.000000000000001
P-value: 0.19914827347145564
Degrees of freedom: 4
Expected frequencies: [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [3]:
df

men  women
0  Увеличивается сумма покупки   21     16
1    Не меняется сумма покупки   75     60
2    Уменьшается сумма покупки    5     10

In [6]:
bambucha = ([21, 75, 5], [16, 60, 10])

In [8]:
# Применение хи-квадрат теста
chi2, p_value, dof, expected = chi2_contingency(bambucha)

print("Chi-square statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:", expected)

Chi-square statistic: 2.8239706434502656
P-value: 0.24365906101675808
Degrees of freedom: 2
Expected frequencies: [[19.98395722 72.9144385   8.10160428]
 [17.01604278 62.0855615   6.89839572]]


In [9]:
chi2_contingency(bambucha)

(2.8239706434502656,
 0.24365906101675808,
 2,
 array([[19.98395722, 72.9144385 ,  8.10160428],
        [17.01604278, 62.0855615 ,  6.89839572]]))